version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
    environment:
      - POSTGRES_USER=signal-cli-rest-api
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=signal-cli-rest-api
  db:
    image: 'postgres:14'
    container_name: signal-cli-rest-api-db
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=signal-cli-rest-api
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=signal-cli-rest-api